### ISSUE TITLE
Concurrency issue with bitbucket

### ISSUE THREAD

**Issue by RemiBou** [jfrog/froggit-go#3]
On this file 
https://github.com/jfrog/froggit-go/blob/40ca96b66fb0aef79adf9d8814f40af7682b7552/vcsclient/bitbucketcloud.go#L23
We get the url via environment variable so if we need multiple bitbucket call in parallel, they might use a wrong value

**Comment by RemiBou** [comment]
@yahavi any idea ? Is this URL per account or is it common to everyone ?

**Comment by yahavi** [comment]
@cyrilc-pro @RemiBou I created https://github.com/jfrog/froggit-go/pull/8 to resolve this issue.
Would you like to review it?
