### ISSUE TITLE
GitLabWebhook.parsePushEvent method panics

### ISSUE THREAD

**Issue by pavelmemory** [jfrog/froggit-go#30]
**Describe the bug**
Method `parsePushEvent` of the `GitLabWebhook` type `panic`s in case there are no commits related to the event.
The actual [code](https://github.com/jfrog/froggit-go/blob/6eb4a68006078b63874a567bab13f2c2269e9293/vcsutils/webhookparser/gitlab.go#L60) that causes the issue `Timestamp:  event.Commits[0].Timestamp.Local().Unix(),`

**Expected behavior**
No panic to be generated.

- Froggit-Go version: https://github.com/jfrog/froggit-go/releases/tag/v1.0.0
- Operating system:

**Additional context**

**Comment by eyalbe4** [comment]
Thanks for reporting this issue @pavelmemory.
If you're able to contribute the fix for this issue, we'd truly appreciate it.
